import type { Metadata } from "next";
import { FC } from "react";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import ScrollToTop from "@/utils/ScrollToTop";
import "../components/Navbar/navbar.css";
import "../styles/style.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/style.css";
import "../components/Presentation/presentation.css";
import "../components/Vision/vision.css";
import "../components/Services/services.css";
import "../components/Skills/skills.css";
import "../components/SupportBusiness/supportBusiness.css";
import "../components/ContactUs/contactUs.css";
import "../components/Footer/footer.css";
import "./about/about.css";
import "../components/AboutUs/aboutus.css";
import "../components/Values/values.css";
import "../components/Team/team.css";
import "../components/MyTeam/myteam.css";

export const metadata: Metadata = {
  title: "nebula App",
  description: "Generated by create next app",
};

interface AppProps {
  Component: FC;
  pageProps: any;
}

const MyApp: FC<AppProps> = ({ Component, pageProps }) => {
  return (
    <>
      <Navbar />
      <Component {...pageProps} />
      <ScrollToTop />
      <Footer />
    </>
  );
};

export default MyApp;
